AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  s3bucketsync:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: ''
      MemorySize: 256
      Timeout: 300
      Role: >-
        arn:aws:iam::365643640437:role/service-role/s3bucket_sync-role-nu1j1up5
      Events:
        SQS1:
          Type: SQS
          Properties:
            Queue:
              'Fn::GetAtt':
                - SQSQueue1
                - Arn
            BatchSize: 5
      Environment:
        Variables:
          CLOUDINARY_URL: cloudinary://123:abc@my_cloud/my_cloud-res.cloudinary.com?cname=my_cloud-res.cloudinary.com
          cld_delivery_url: 'https://my_cloud-res.cloudinary.com'
          cld_sync_root: s3_sync
          notification_topic: 'sns_topic'
          s3_sync_root: sync_cloudinary
          skip_reload_same_etag: 'false'
  SQSQueue1:
    Type: 'AWS::SQS::Queue'
    Properties: {}